# Generated by Django 3.1.6 on 2021-03-18 11:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('upload_data', '0007_auto_20210222_1236'),
    ]

    operations = [
        migrations.CreateModel(
            name='FontStyle',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('font_type', models.TextField(default='aerial.ttf')),
            ],
        ),
        migrations.AlterField(
            model_name='certificate',
            name='font_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='fonttype', to='upload_data.fontstyle'),
        ),
    ]
