# Generated by Django 3.1.6 on 2021-03-18 11:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('upload_data', '0009_auto_20210318_1707'),
    ]

    operations = [
        migrations.AlterField(
            model_name='certificate',
            name='event_name_position_x',
            field=models.IntegerField(default=2),
        ),
        migrations.AlterField(
            model_name='certificate',
            name='event_name_position_y',
            field=models.IntegerField(default=2),
        ),
        migrations.AlterField(
            model_name='certificate',
            name='font_size',
            field=models.IntegerField(default=2),
        ),
        migrations.AlterField(
            model_name='certificate',
            name='participate_name_position_x',
            field=models.IntegerField(default=2),
        ),
        migrations.AlterField(
            model_name='certificate',
            name='participate_name_position_y',
            field=models.IntegerField(default=2),
        ),
        migrations.AlterField(
            model_name='certificate',
            name='qr_code_position_x',
            field=models.IntegerField(default=2),
        ),
        migrations.AlterField(
            model_name='certificate',
            name='qr_code_position_y',
            field=models.IntegerField(default=2),
        ),
        migrations.AlterField(
            model_name='certificate',
            name='qr_code_size_x',
            field=models.IntegerField(default=2),
        ),
        migrations.AlterField(
            model_name='certificate',
            name='qr_code_size_y',
            field=models.IntegerField(default=2),
        ),
    ]
