# Generated by Django 3.1.6 on 2021-03-28 05:04

from django.db import migrations, models
import django_dropbox_storage.storage


class Migration(migrations.Migration):

    dependencies = [
        ('upload_data', '0010_auto_20210318_1715'),
    ]

    operations = [
        migrations.AlterField(
            model_name='certificate',
            name='image',
            field=models.ImageField(storage=django_dropbox_storage.storage.DropboxStorage(), upload_to='certificates/'),
        ),
    ]
