# Generated by Django 3.1.6 on 2021-03-16 08:01

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Board_Certificate',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='certificates/')),
                ('text_color_R', models.IntegerField(default=0)),
                ('text_color_G', models.IntegerField(default=0)),
                ('text_color_B', models.IntegerField(default=0)),
                ('font_size', models.IntegerField(default=0)),
                ('font_type', models.TextField(blank=True, max_length=50)),
                ('board_name_location_x', models.IntegerField(default=0)),
                ('board_name_location_y', models.IntegerField(default=0)),
                ('boardposition_name_location_x', models.IntegerField(default=0)),
                ('boardposition_name_location_y', models.IntegerField(default=0)),
                ('qr_code_location_x', models.IntegerField(default=0)),
                ('qr_code_location_y', models.IntegerField(default=0)),
                ('qr_code_size_x', models.IntegerField(default=0)),
                ('qr_code_size_y', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='Board_member_details',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Board_Full_Name', models.TextField(max_length=50)),
                ('Designation', models.TextField(max_length=50)),
                ('Description_n_about', models.TextField()),
                ('Photo', models.ImageField(blank=True, upload_to='board_photos')),
                ('slug', models.SlugField(blank=True, null=True)),
            ],
        ),
    ]
