# Generated by Django 3.1.6 on 2021-03-16 08:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('board_cert', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='board_certificate',
            name='Designation',
            field=models.TextField(default=None),
        ),
        migrations.AlterField(
            model_name='board_member_details',
            name='Designation',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='eventsname', to='board_cert.board_certificate'),
        ),
    ]
