# Generated by Django 3.1.6 on 2021-03-18 11:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('upload_data', '0010_auto_20210318_1715'),
        ('board_cert', '0002_auto_20210316_1343'),
    ]

    operations = [
        migrations.AlterField(
            model_name='board_certificate',
            name='font_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='fontType', to='upload_data.fontstyle'),
        ),
    ]
