# Generated by Django 3.1.6 on 2021-03-20 04:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('board_cert', '0003_auto_20210318_1715'),
    ]

    operations = [
        migrations.AddField(
            model_name='board_member_details',
            name='facebook_link',
            field=models.TextField(default='', max_length=250),
        ),
        migrations.AddField(
            model_name='board_member_details',
            name='github_link',
            field=models.TextField(default='', max_length=250),
        ),
        migrations.AddField(
            model_name='board_member_details',
            name='linkedin_link',
            field=models.TextField(default='', max_length=250),
        ),
    ]
