# Generated by Django 3.1.6 on 2021-03-20 07:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('board_cert', '0004_auto_20210320_1000'),
    ]

    operations = [
        migrations.AlterField(
            model_name='board_certificate',
            name='board_name_location_x',
            field=models.IntegerField(default=2),
        ),
        migrations.AlterField(
            model_name='board_certificate',
            name='board_name_location_y',
            field=models.IntegerField(default=2),
        ),
        migrations.AlterField(
            model_name='board_certificate',
            name='boardposition_name_location_x',
            field=models.IntegerField(default=2),
        ),
        migrations.AlterField(
            model_name='board_certificate',
            name='boardposition_name_location_y',
            field=models.IntegerField(default=2),
        ),
        migrations.AlterField(
            model_name='board_certificate',
            name='font_size',
            field=models.IntegerField(default=2),
        ),
        migrations.AlterField(
            model_name='board_certificate',
            name='qr_code_location_x',
            field=models.IntegerField(default=2),
        ),
        migrations.AlterField(
            model_name='board_certificate',
            name='qr_code_location_y',
            field=models.IntegerField(default=2),
        ),
        migrations.AlterField(
            model_name='board_certificate',
            name='qr_code_size_x',
            field=models.IntegerField(default=2),
        ),
        migrations.AlterField(
            model_name='board_certificate',
            name='qr_code_size_y',
            field=models.IntegerField(default=2),
        ),
    ]
